### ISSUE TITLE
Sprint 1 Uh1tk8: Conectar y configurar sensor de gases en el aire MQ135

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-preprocesamiento-grupo-plata#12]
**Uh1tk8: Conectar y configurar sensor de gases en el aire MQ135**

**Objetivo:**

Conectar y configurar un sensor MQ135 en el ESP32-Wroom.  

**Pasos a seguir:**

**1.** Revisar el datasheet del sensor MQ135 para identificar las conexiones necesarias.
**2.** Conectar el sensor a los pines adecuados del ESP32-Wroom.
**3.** Escribir el código para leer los datos del sensor.
**4.** Verificar la correcta lectura de los datos mediante pruebas en diferentes condiciones de humedad.

**Comment by NicolasBa27** [comment]
![image](https://github.com/user-attachments/assets/ed606de6-7d7f-4c75-9eed-4e1c1fc6735f)
