### ISSUE TITLE
Sprint 1 Uh1tk1: Configurar Visual Studio Code

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-preprocesamiento-grupo-plata#5]
**Sprint 1: 12/08 - 18/08**  

**Uh1tk1: Configurar Visual Studio Code**

**Objetivo:**

Instalar Visual Studio Code en el entorno de desarrollo.  

**Pasos a seguir:**

- Visitar el [sitio oficial de Visual Studio Code](https://code.visualstudio.com/).
- Descargar la versión adecuada para tu sistema operativo.
- Ejecutar el instalador y seguir las instrucciones en pantalla.
- Verificar que Visual Studio Code se haya instalado correctamente abriéndolo.

**Comment by pleroldan** [comment]
## configuracion:
Se adjunta configuracion inicial de VSCode


![image](https://github.com/user-attachments/assets/597407e7-5161-4027-aead-8fb510e919c5)

**Comment by FerCbr** [comment]
Se adjunta imagen configuracion inicial VSCode

![Image](https://github.com/user-attachments/assets/cd901841-7f06-40e7-83fa-622e1f5ecbb6)

**Comment by NicolasBa27** [comment]
Se adjunta imagen configuración inicial VSCode.



![Image](https://github.com/user-attachments/assets/760c6e3d-75f0-4d80-8079-937dadb74e36)

**Comment by r-j28** [comment]
Configuracion VSCode
![Captura de pantalla (224)](https://github.com/user-attachments/assets/61989f2a-2c01-4309-911f-5ec350f8478c)

**Comment by MacarenaAC** [comment]
Se adjunta imagen de configuracion de VSCode
![visualcode](https://github.com/user-attachments/assets/134af169-5a1c-4b30-8dba-9376d5eb7dbd)

**Comment by FerCbr** [comment]
Se cierra la issue con la mayoría de los integrantes habiendo configurado Vscode
