### ISSUE TITLE
Sprint 1 Uh1tk2: Configurar PlatformIO en VS Code

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-preprocesamiento-grupo-plata#6]
**Uh1tk2: Configurar PlatformIO en VS Code**

**Objetivo:**

Instalar y configurar PlatformIO como extensión en Visual Studio Code para el desarrollo de proyectos IoT.  

**Pasos a seguir:**

**1.** Abrir Visual Studio Code.
**2.** Navegar a la sección de extensiones (icono de cuadrado en la barra lateral izquierda).
**3.** Buscar "PlatformIO IDE" en la barra de búsqueda.
**4.** Instalar la extensión.
**5.** Reiniciar Visual Studio Code para que los cambios tomen efecto.
**6.** Verificar la correcta instalación creando un nuevo proyecto PlatformIO.

**Comment by pleroldan** [comment]
# platformio:

![image](https://github.com/user-attachments/assets/155b0ded-12e9-49dc-a801-bc2616369084)

**Comment by FerCbr** [comment]
Adjunto imagen con configuracion inicial de Platformio



![Image](https://github.com/user-attachments/assets/560d524a-91cc-4275-aaa0-fbdc246af107)

**Comment by karina-lolis** [comment]
Adjunto imagen con configuración inicial de PlatformIO. 
![pioimag](https://github.com/user-attachments/assets/cbe0f80a-121c-46a8-85f9-a7bb4116cfca)

**Comment by NicolasBa27** [comment]
Adjunto imagen con configuración inicial de Platformio.



![Image](https://github.com/user-attachments/assets/ab158f50-90c8-43e0-9ede-5858336acb72)

**Comment by r-j28** [comment]
Adjunto primeras configuraciones en VSCode con PlatformIO
![Captura de pantalla (225)](https://github.com/user-attachments/assets/3f923d8a-c66c-46dc-890e-5f487a0df5c2)
formio.

**Comment by MacarenaAC** [comment]
Adjunto imagen con configuración inicial de Platformio.
![PLATFORMIO](https://github.com/user-attachments/assets/3e81d5ac-be6e-4a6d-bd96-f69c01ce2c85)

**Comment by FerCbr** [comment]
Se cierra issue con la mayoría de los integrantes habiendo configurado PlatformIO
