### ISSUE TITLE
Sprint 1 Uh1tk4: Investigar casos de uso de Edge Computing en IoT

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-preprocesamiento-grupo-plata#8]
**Uh1tk4: Investigar casos de uso de Edge Computing en IoT**

**Objetivo:**

Investigar y documentar 3 casos de uso de Edge Computing en proyectos IoT.  

**Pasos a seguir:**

**1.** Realizar una búsqueda en internet sobre Edge Computing aplicado a IoT.
**2.** Seleccionar tres casos de uso que sean relevantes para el proyecto.
**3.** Documentar cada caso de uso, incluyendo descripción, beneficios, y desafíos.
**4.** Preparar una breve presentación de los casos para la discusión en el equipo.

**Comment by NicolasBa27** [comment]
Issue uh1tk4 finalizada.
